import type { AdminListingFormData } from "@/components/admin-listing-form";

export function createEmptyFormData(type: "RENT" | "SALE" = "RENT"): AdminListingFormData {
  return {
    title: "",
    features: ["", "", "", "", "", ""],
    city: "",
    district: "",
    address: "",
    community: "",
    listingType: type,
    propertyType: "APARTMENT",
    price: "",
    areaPing: "",
    areaMain: "",
    areaAncillary: "",
    areaCommon: "",
    areaLand: "",
    areaParkingSpace: "",
    parkingPrice: "",
    parkingSpaceInfo: "",
    parkingRent: "",
    parkingType: "",
    parkingIncluded: "",
    managementFee: "",
    petsAllowed: "",
    taxDeductible: "",
    rentSubsidy: "",
    canRegisterAddress: "",
    viewingMethod: "",
    buildingAge: "",
    orientation: "",
    decorLevel: "",
    usageZoning: "",
    hasElevator: "",
    legalUsage: "",
    mrtLine: "",
    mrtStation: "",
    videoUrl: "",
    rooms: "",
    livingRooms: "",
    balconies: "",
    bathrooms: "",
    floor: "",
    totalFloors: "",
    coverImage: "",
    images: [],
    contactName: "",
    contactPhone: "",
    ownerIdCardUrl: "",
    furnitureProvided: "",
    applianceProvided: "",
    shortTermRent: "",
    serviceFee: "",
    registrationUse: "",
    securityDeposit: "",
    availableFrom: "",
    householdsPerFloor: "",
    isPublished: true,
  };
}
